name: "Chapter Three"
on: push
env:
    ARTIFACT_NAME: myartifact
jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
          - name: "Checkout"
            uses: actions/checkout@v4
          - name: "Upload"
            uses: actions/upload-artifact@v4
            with:
                name: ${{env.ARTIFACT_NAME}}
                path: "./"
